name: time_capsule
description: A time capsule app for NH members.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  uuid: ^4.2.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  sqflite_common_ffi_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/treasure_box_closed.png
    - assets/treasure_box_open.png 